
# This workflow will install Octave and run unit tests and the demos

name: Octave application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y octave octave-dev octave-image
    - name: Compile
      run: |
        cd code
        octave --no-gui compile.m
    - name: Run line demo
      run: |
        cd code/line_fitting
        octave --no-gui --eval "pkg load image; demo_line_fitting"
    - name: Run circle demo
      run: |
        cd code/circle_fitting
        octave --no-gui --eval "pkg load image; demo_circle_fitting"
    - name: Run ellipse demo
      run: |
        cd code/arbitrary_ellipse_fitting
        octave --no-gui --eval "pkg load image; demo_ellipse_fitting"
    - name: Run spline contour demo
      run: |
        cd code/spline_contour_fitting
        octave --no-gui --eval "pkg load image; demo_spline_contour_fitting"
